server:
  port: 9200

spring:
  application:
    name: maxs-system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/maxs?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    password:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 63deb4d5-bd36-4b05-9d7c-0cc579e5002f
      config:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  sentinel:
    enabled: true