server:
  port: 9000

spring:
  application:
    name: maxs-gateway
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
    # 应用名称
    name: maxs-gateway
  cloud:
    # 使用 Nacos 作为服务注册发现
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 63deb4d5-bd36-4b05-9d7c-0cc579e5002f
    # 使用 Sentinel 作为熔断器
    sentinel:
      transport:
        port: 8721
        dashboard: localhost:8080
    # 路由网关配置
    gateway:
      # 设置与服务注册发现组件结合，这样可以采用服务名的路由策略
      discovery:
        locator:
          enabled: true
      # 配置路由规则
      routes:
        # 采用自定义路由 ID（有固定用法，不同的 id 有不同的功能，详见：https://cloud.spring.io/spring-cloud-gateway/2.0.x/single/spring-cloud-gateway.html#gateway-route-filters）
        - id: MAXS-BUSINESS-ONE
          # 采用 LoadBalanceClient 方式请求，以 lb:// 开头，后面的是注册在 Nacos 上的服务名
          uri: lb://maxs-business-one
          # Predicate 翻译过来是“谓词”的意思，必须，主要作用是匹配用户的请求，有很多种用法
          predicates:
            # Method 方法谓词，这里是匹配 GET 和 POST 请求
            - Method=GET,POST,PUT,DELETE
        - id: MAXS-SYSTEM
          uri: lb://maxs-system
          predicates:
            - Method=GET,POST,PUT,DELETE
        # 认证中心
        - id: MAXS-AUTH
          uri: lb://maxs-auth
          predicates:
            - Path=/oauth/**



# 开启熔断机制
feign:
  sentinel:
    enabled: true

# 暴露所以端点
management:
  endpoints:
    web:
      exposure:
        include: "*"

# 配置日志级别，方便调试
logging:
  level:
    org.springframework.cloud.gateway: debug
